### ISSUE TITLE
Error "Could not find com.github.hannesa2:AndroidSlidingUpPanel:3.5.0." when added in gradle & sync

### ISSUE THREAD

**Issue by poncoe** [hannesa2/AndroidSlidingUpPanel#120]
hi, i dont know what happen when im continue my old project, after 3 years I didn't continue, every i sync project, in build output always says

 "  Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.hannesa2:AndroidSlidingUpPanel:3.5.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/hannesa2/AndroidSlidingUpPanel/3.5.0/AndroidSlidingUpPanel-3.5.0.pom
       - https://jcenter.bintray.com/com/github/hannesa2/AndroidSlidingUpPanel/3.5.0/AndroidSlidingUpPanel-3.5.0.pom
       - https://repo.maven.apache.org/maven2/com/github/hannesa2/AndroidSlidingUpPanel/3.5.0/AndroidSlidingUpPanel-3.5.0.pom
       - https://jitpack.io/com/github/hannesa2/AndroidSlidingUpPanel/3.5.0/AndroidSlidingUpPanel-3.5.0.pom
     Required by:
         project :app "
         
here my gradle root : 

> 

buildscript {

    repositories {
        google()
        mavenCentral()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.1.3"
        classpath 'com.google.gms:google-services:4.3.13'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

> allprojects {

    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

> task clean(type: Delete) {

    delete rootProject.buildDir
}`

in my gradle app, i added `implementation 'com.github.hannesa2:AndroidSlidingUpPanel:3.5.0'` , 

i hope you have this solution, thanks.

**Comment by hannesa2** [comment]
It looks like I remove some older versions, please use on of these https://github.com/hannesa2/AndroidSlidingUpPanel/releases
