### ISSUE TITLE
Crash with androidx

### ISSUE THREAD

**Issue by Allosh87** [hannesa2/AndroidSlidingUpPanel#16]
My app crashes on startup just by adding the library in the gradle.

at music.player.allosh.MainActivity.onCreate(MainActivity.java:48)
06-11 18:46:24.004 14661 14661 E   AndroidRuntime                               at android.app.Activity.performCreate(Activity.java:7955)
06-11 18:46:24.004 14661 14661 E   AndroidRuntime                               at android.app.Activity.performCreate(Activity.java:7944)
06-11 18:46:24.004 14661 14661 E   AndroidRuntime                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
06-11 18:46:24.004 14661 14661 E   AndroidRuntime                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)
06-11 18:46:24.004 14661 14661 E   AndroidRuntime                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
06-11 18:46:24.004 14661 14661 E   AndroidRuntime                               at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
06-11 18:46:24.004 14661 14661 E   AndroidRuntime                               at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
06-11 18:47:50.128 15595 15595 E   RecyclerView 

Now the MainActivity line causing the error is the method
setupViewPager();

**Comment by hannesa2** [comment]
Without knowing your code, maybe the library with supportlib is the right one for you ?

`implementation 'com.github.hannesa2:AndroidSlidingUpPanel:3.5.0`

**Comment by Allosh87** [comment]
Oops! Sorry I forgot that I posted an issue here. Using the support version throws a couple of errors " attribute has already been defined". I'm using androidx libraries along with the library so I think there are some duplicates

**Comment by hannesa2** [comment]
> Using the support version ...
> I'm using androidx libraries along with the library ...

It's a kind of confusing. Without knowing your code, I can't do much

**Comment by Allosh87** [comment]
I'm not pushing you to do anything. Maybe the IDE that I'm using is the cause of this problem. I'll try to figure it out. Thanks.
