### ISSUE TITLE
Height recall on changing panelState

### ISSUE THREAD

**Issue by Doomsdayrs** [hannesa2/AndroidSlidingUpPanel#18]
Example, currentX means the current state of the value
```kotlin
currentPanelState == COLLAPSED
currentPanelHeight == 238

panelState = HIDDEN // Hides the panel
postDelayed({
    currentPanelState == HIDDEN
    currentPanelHeight == 238
},500)
```

I can do a force to change the height from 238 to 0, which finally hides the white bare left behind when the panel is hidden. If I do not force the change, the panel goes from COLLAPSED to HIDDEN, With height going from 238 -> 0 -> 238 (which creates a bounce back effect)

**Comment by Doomsdayrs** [comment]
This function, when called should fix the height, but its a dirty solution
```kotlin
	private fun fixHeight() {
		slidingUpPanelLayout.apply {
			val state = panelState
			Log.d(logID(), "PanelState is now ${state.name}")
			when (state) {
				PanelState.HIDDEN -> panelHeight = 0
				PanelState.COLLAPSED -> panelHeight = 238
				PanelState.DRAGGING -> postDelayed(100) { fixHeight() }
				else -> Log.d(logID(), "Unknown state: $state")
			}
		}
	}
```

**Comment by hannesa2** [comment]
I'm happy to approve any good solution
