### ISSUE TITLE
Make mSlideableView public

### ISSUE THREAD

**Issue by omkar-tenkale** [hannesa2/AndroidSlidingUpPanel#21]
Or add a method getSlideableView?

Usage: to manually animate the slideview for short time span

**Comment by hannesa2** [comment]
Here it is https://github.com/hannesa2/AndroidSlidingUpPanel/pull/26

Btw, I'm happy to accept pull requests as well

**Comment by hannesa2** [comment]
Here you go https://github.com/hannesa2/AndroidSlidingUpPanel/releases/tag/4.2.1

`implementation 'com.github.hannesa2:AndroidSlidingUpPanel:4.2.1'`

**Comment by omkar-tenkale** [comment]
Great,thanks!
