### ISSUE TITLE
Redundant implementation.

### ISSUE THREAD

**Issue by liuxiaoliu66** [hannesa2/AndroidSlidingUpPanel#78]
`dependencies {
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
    implementation "androidx.core:core-ktx:+"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
`
Can already satisfy the use,
unnecessary
` implementation 'androidx.legacy:legacy-support-v4:1.0.0'`
`implementation 'androidx.annotation:annotation:1.3.0'`

**Comment by hannesa2** [comment]
Thank you https://github.com/hannesa2/AndroidSlidingUpPanel/pull/79
