### ISSUE TITLE
Broken scrolling up.

### ISSUE THREAD

**Issue by Makarezp** [hannesa2/AndroidSlidingUpPanel#82]
Hey #72 broken scrolling dragView up!

**Comment by hannesa2** [comment]
Did you investigate what exactly broke it ?

@838239178 for your info

**Comment by 838239178** [comment]
i don't understand what problem exactly happened?

**Comment by Makarezp** [comment]
I did not investigate exactly what is the cause. 
@838239178 Compare behaviour of test test app before and after the commit. Scroll down the panel content and try to scroll it up. Rather than expected scrolling of the content panel takes over the event and moves over to dragging state. Content scrolling is just one way.

**Comment by 838239178** [comment]
OK. I got it and I will find out the resolution.

**Comment by hannesa2** [comment]
Thanks to @838239178 we have this https://github.com/hannesa2/AndroidSlidingUpPanel/releases/tag/4.3.2
