### ISSUE TITLE
Class ScrollableViewHelper cannot be extended

### ISSUE THREAD

**Issue by ZXHHYJ** [hannesa2/AndroidSlidingUpPanel#88]
You forgot to add the "open" modifier when converting kotlin

**Comment by hannesa2** [comment]
When you tell me where you miss it ? 
I would rater say, I didn't need it till now.

Btw, this is a contribution repository, I'll approve almost any pull request

**Comment by ZXHHYJ** [comment]
in com.sothree.slidinguppanel.ScrollableViewHelper.Just add "open", thank you very much

my english is poor......

**Comment by hannesa2** [comment]
Here you go https://github.com/hannesa2/AndroidSlidingUpPanel/releases/tag/4.4.0
