### ISSUE TITLE
There is a bug in class ScrollableViewHelper

### ISSUE THREAD

**Issue by ZXHHYJ** [hannesa2/AndroidSlidingUpPanel#91]
The getScrollableViewScrollPosition function in class ScrollableViewHelper cannot be overridden because it is final.
![image](https://user-images.githubusercontent.com/32431375/152355007-ee65c15d-18b6-4288-ad76-c62ecfba060f.png)

**Comment by hannesa2** [comment]
You make a lot of noise and https://github.com/hannesa2/AndroidSlidingUpPanel/issues/88 comes with a solution.
If you need more, please open a pull request
